name: dinov2
channels:
  - pytorch
  - nvidia
  - xformers
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchvision=0.16.0
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers>=0.0.22  # This version is key for CUDA 12.1
  - pip
  - pip:
      - git+https://github.com/facebookincubator/submitit
      - --extra-index-url https://pypi.nvidia.com
      - cuml-cu12